# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('package', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('childCount', models.IntegerField(default=130)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('coeliac', models.CharField(blank=True, max_length=250)),
                ('vegetarian', models.CharField(blank=True, max_length=250)),
                ('vegan', models.CharField(blank=True, max_length=250)),
                ('milk_intolerant', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MealGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.MealGroup'),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='food.IngredientInMeal', to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientinmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Meal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.IngredientGroup'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Supplier'),
        ),
    ]
