# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredient_import',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
