# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_meal_ingredient_import'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='ingredientinmeal',
            old_name='count',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='food.IngredientInMeal', to='food.Ingredient'),
        ),
    ]
