# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20170212_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('childCount', models.IntegerField()),
                ('meals', models.ManyToManyField(to='food.Meal')),
            ],
        ),
    ]
