# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20170213_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='side',
            old_name='value',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='side',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
