# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20170213_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='price',
            field=models.FloatField(),
        ),
    ]
