# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20170213_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meals',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meal'),
        ),
    ]
