# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_side_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='meals',
            new_name='meal',
        ),
    ]
