# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20170304_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end',
            field=models.DateField(blank=True, help_text="Don't fill"),
        ),
        migrations.AlterField(
            model_name='term',
            name='weeks',
            field=models.IntegerField(default=10),
        ),
    ]
