# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20170304_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
