# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20170805_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='picture',
        ),
        migrations.AddField(
            model_name='meal',
            name='picture_url',
            field=models.URLField(blank=True),
        ),
    ]
